name: Test
on: [push]
jobs:
  MACOS:
    name: MACOS
    runs-on: macos-14
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: compile
        run: gcc -o pthread pthread.c -lpthread
      - name: RUN
        run: ./pthread
      - name: RUN
        run: ./pthread2
      - name: check
        run: uname -m
      - name: check2
        run: system_profiler SPHardwareDataType
